### ISSUE TITLE
Uncaught exception 'DailymotionTransportException' with message 'name lookup timed out' 

### ISSUE THREAD

**Issue by cicklow** [dailymotion/dailymotion-sdk-php#37]
3 days ago from api not working me well, giving me this error:
Fatal error</b>:  Uncaught exception 'DailymotionTransportException' with message 'name lookup timed out' in daily/Dailymotion.php:855
Stack trace:
#0 daily/Dailymotion.php(325): Dailymotion-&gt;httpRequest('http://upload-1...', Array)
#1 daily/daily_up.php(30): Dailymotion-&gt;uploadFile('../video.mov')
#2 {main}

and

Fatal error: Uncaught exception 'DailymotionTransportException' with message 'name lookup timed out' in daily/Dailymotion.php:855
Stack trace:
#0 daily/Dailymotion.php(714): Dailymotion->httpRequest('https://api.dai...', Array, NULL, NULL, Array, true)
#1 daily/Dailymotion.php(578): Dailymotion->oauthTokenRequest(Array)
#2 daily/Dailymotion.php(391): Dailymotion->getAccessToken()
#3 daily/Dailymotion.php(343): Dailymotion->call('GET /file/uploa...', Array)
#4 daily/Dailymotion.php(313): Dailymotion->get('/file/upload')
#5 daily/daily_up.php(30): Dailymotion->uploadFile('../video.mov')
#6 {main}
  thrown in daily/Dailymotion.php on line 855

**Comment by NykO18** [comment]
Things like this can happen. The `name lookup timed out` error of cURL usually comes from the server not being able to resolve the address you're trying to access. This again is most often due to the server not having a working connection with the Internet. If the problem is isolated and doesn't happen constantly, it means that it was only a temporary outage of the service. You need to protect your code against such events by catching all `DailymotionTransportException` and failing gracefully. If this happens on a fairly regular basis, please don't hesitate to tell us.

**Comment by gamebak** [comment]
Hey, I am having same problem recently. The traffic has been pretty much the same ~13-15k hits, but recently it grew when I changed my server.
I increased my caching time to 1 minute to lower the requests, but even like that this happends.

Do you have any solutions for this ? I was thinking to increase curl time limit.
