### ISSUE TITLE
Can't create a video

### ISSUE THREAD

**Issue by LR3my** [dailymotion/dailymotion-sdk-php#50]
Hello,

I'm trying to upload and create a video using this code 

```
$api = new Dailymotion();

 $api->setGrantType(
            Dailymotion::GRANT_TYPE_PASSWORD,
            $dailymotion_api_key,
            $dailymotion_secret,
            array('read', 'write', 'delete', 'manage_videos'),
            array('username' => 'xxxxxxxx', 'password' => 'xxxxxxxxx')
        );

        $url = $api->uploadFile('path/to/file');

        $result = $api->post('/me/videos', array('url' => $url));
```

But I keep geeting this error : 

> 'Unsufficient scope for `POST /user/<id>/videos', scope required: manage_videos'

I'm granting "manage_videos" scope, I really don't get it, can it come from my api conf' ?

**Comment by MathildeS** [comment]
If you're passing the `manage_videos scope` and still get an error mentioning you don't have the correct scope, it must be due to an existing section.

One of the problems with OAuth 2.0 is that the specification doesn't offer any mechanism to upgrade the scope of an existing session. To add new scopes to an already existing session, you first need to call the Dailymotion::logout() method and start a new session with your new list of scopes (see the note mentioning this at https://developer.dailymotion.com/tools/sdks#sdk-php-authentication ).
